Домашняя работа №2 (Сверстать модальное окно карточки товара)
kasyanov2393/Kolesa-Upgrade-FE-2021 pull request #2
Opened 2021-09-25 19:20 UTC by kasyanov2393

Основное модальное окно:
-Отцентровано на странице по вертикали и горизонтали. **(готово)**
-Высота не фиксированная и зависит от контента. **(готово)**
-Ширина фиксированная, но может меняться если отстуствет блок с фото. **(готово)**
-Обязаталеьные блоки: Заголовок товара, стоимость товара, кнопка действия, блок “твой баланс”. Всех остальных элементов может не быть, нужно это предусмотреть чтобы верстка не взорвалась. **(готово)**

Блок с фото:
-Количество фоток в блоке превью может быть любым. Предусмотреть правильную многострочность.  **(готово)**
-Добавить класс для “активной” превьюшки. **(готово)**

Блок с опциями товара(цвет, размер):
Количество опций может быть любым. Предусмотреть правильную многострочность. **(готово)**
(*) Реализовать функционал переключения опций через radio-buttons **(готово)**

2021-09-27 11:06 UTC, vitaliytsoy commented
В целом не плохо
Радуют сообщения коммитов и название ПР
И использование БЕМ

2021-09-27 14:35 UTC, vitaliytsoy requested changes

2021-09-27 15:42 UTC, kasyanov2393 commented on index.html
> +            <div data-close class="modal__close">
**Done**
Исправил div на button

2021-09-27 16:03 UTC, kasyanov2393 commented on index.html
> +                <span></span>
**Done**

2021-09-27 16:16 UTC, kasyanov2393 commented on src/css/style.css
> +    position: absolute;
**Done**
Проверил заголовок
![image](https://user-images.githubusercontent.com/79243121/134946404-40e88eb7-8a23-43d7-9792-2612446cacff.png)

2021-09-27 16:29 UTC, kasyanov2393 commented on src/css/style.css
> +    padding: 8px;
**Done**
![image](https://user-images.githubusercontent.com/79243121/134948491-4611f629-56b8-492a-8deb-c459e6dfb012.png)

2021-09-27 16:33 UTC, kasyanov2393 commented on src/css/style.css
> +.modal__colors_btn label {
**Done**

2021-09-27 17:07 UTC, kasyanov2393 commented on index.html
> +                    <img src="/src/assets/img/image_card_product.jpg" alt="image_card_product" width="330" height="330">
**Done**
Проверил object-fit
![image](https://user-images.githubusercontent.com/79243121/134954291-4ecd1b16-a0a6-47a8-a6f2-004917eff25c.png)

2021-09-27 17:08 UTC, kasyanov2393 commented on src/css/style.css
> +    margin-top: 16px;
**Done**

2021-09-27 17:21 UTC, kasyanov2393 commented on index.html
> +                    <img src="/src/assets/img/image_modal.jpg" alt="image_modal_miniature" id="modal__image-active">
**Done**

"Кроме инпутов, id лучше вообще никогда не использовать" - исправил

"Если хочешь по бэму добавб класс модификатор для активного состояния" - >>> Так modal__image-mini_active ??

2021-09-27 17:21 UTC, kasyanov2393 commented on src/js/main.js
> +/* document.querySelector('#app').innerHTML = `
**Done**

2021-09-27 18:38 UTC, kasyanov2393 commented on index.html
> +                            <input id="color-radio-1" type="radio" name="radio" value="1" checked>
Интересно, почитаю-погуглю и исправлю позже т.к не критично :)

2021-09-27 18:39 UTC, kasyanov2393 commented on src/css/style.css
> +    margin-top: 11px;
**Done**

2021-09-28 07:35 UTC, vitaliytsoy commented on index.html
> +                    <img src="/src/assets/img/image_modal.jpg" alt="image_modal_miniature" id="modal__image-active">
По БЕМу модификаторы задаются через двойное тире
`modal__image--active`

2021-09-28 07:36 UTC, vitaliytsoy approved these changes

2021-09-28 08:11 UTC, merged